# Generated by Django 4.2.5 on 2024-07-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("khata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
    ]
