# Generated by Django 4.2.5 on 2024-07-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("khata", "0002_alter_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
