# Generated by Django 4.2.5 on 2024-08-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("khata", "0003_alter_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyloan",
            name="loanType",
            field=models.CharField(
                choices=[
                    ("PERSONAL LOAN", "personal loan"),
                    ("VECHICLES LOAN", "vechicles loan"),
                    ("MORTAGE LOAN", "mortage loan"),
                    ("GOLD LOAN", "gold loan"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
